# Resources for the cainjector component
installCRDs: true

rbac: 
 create: true
 
cainjector: 
 resources: 
  requests:
    cpu: "20m"  
    memory: "40Mi"  
  limits:
    cpu: "90m"  
    memory: "180Mi" 
webhook: 
 resources: 
  requests:
    cpu: "20m"  
    memory: "40Mi"  
  limits:
    cpu: "90m"  
    memory: "180Mi" 
controller: 
 resources: 
  requests:
    cpu: "20m"  
    memory: "40Mi"  
  limits:
    cpu: "90m"  
    memory: "180Mi"  