crds: 
 install: true

rbac: 
 create: true
 enabledCustomScaledRefKinds: false

prometheus:
  metricServer:
    enabled: true
    port: 8080
    serviceMonitor:
      enabled: true
      interval: 30s
      scrapeTimeout: 10s
      port: metrics
      scheme: http
      jobLabel: "keda-metric-server"
      additionalLabels:
        release: prometheus
      metricRelabelings: []
      relabelings: []
  operator:
    enabled: true
    port: 8080
    serviceMonitor:
      enabled: true
      interval: 30s
      scrapeTimeout: 10s
      port: metrics
      scheme: http
      jobLabel: "keda-operator"
      additionalLabels:
        release: prometheus
      metricRelabelings: []
      relabelings: []
  webhooks:
    enabled: true
    port: 8080
    serviceMonitor:
      enabled: true
      interval: 30s
      scrapeTimeout: 10s
      port: metrics
      scheme: http
      jobLabel: "keda-webhooks"
      additionalLabels:
        release: prometheus
      metricRelabelings: []
      relabelings: []

resources: 
 operator: 
    requests:
      memory: "20Mi"
      cpu: "50m"
    limits:
      memory: "40Mi"
      cpu: "100m"
 metricServer:
    requests:
      memory: "20Mi"
      cpu: "50m"
    limits:
      memory: "40Mi"
      cpu: "100m"
 webhooks:
    requests:
      memory: "20Mi"
      cpu: "50m"
    limits:
      memory: "40Mi"
      cpu: "100m"
 