
kubeApiServer:
  enabled: true

alertmanager:
  service: 
    type: ClusterIP
    clusterIP: ""
    ports: 
       http: 9093
  resources:
    requests:
      cpu: "10m"
      memory: "20Mi"
    limits:
      cpu: "90m"
      memory: "180Mi"

blackboxExporter:
  resources:
    requests:
      cpu: "10m"
      memory: "20Mi"
    limits:
      cpu: "90m"
      memory: "180Mi"

operator:
  resources:
    requests:
      cpu: "10m"
      memory: "20Mi"
    limits:
      cpu: "90m"
      memory: "180Mi"

prometheus:
  additionalScrapeConfigs:
    enabled: true 
    type: internal
    internal: 
      jobList:
        - job_name: 'keda'
          static_configs:
           - targets: ['keda-operator-metrics-apiserver.keda.svc.cluster.local:8080']
  resources:
    requests:
      cpu: "40m"
      memory: "80Mi"
    limits:
      cpu: "400m"
      memory: "900Mi"
  thanos:
    resources:
      requests:
        cpu: "10m"
        memory: "20Mi"
      limits:
        cpu: "90m"
        memory: "180Mi"

kube-state-metrics:
  resources:
    requests:
      cpu: "10m"
      memory: "20Mi"
    limits:
      cpu: "90m"
      memory: "180Mi"
